[tools]
rotrieve = { source = "roblox/rotriever", version = "0.5.5" }
rojo = { source = "Roblox/rojo-rbx-rojo", version = "7.2.1" }
selene = { source = "Roblox/Kampfkarren-selene", version = "0.20.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "=0.14.3" }
rbx-aged-cli = { source = "Roblox/rbx-aged-tool", version = "5.x.x" }
