[package]
name = "Picomatch"
version = "0.3.0"
authors = [
    "Chris Trześniewski <k.trzesniewski@gmail.com>",
]

content_root = "src"

files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = "github.com/roblox/luau-polyfill@0.4.0"
Promise = "github.com/roblox/roblox-lua-promise@3.3.0"
RegExp = "github.com/roblox/luau-regexp@0.2.0"

[dev_dependencies]
JestGlobals = "github.com/roblox/jest-roblox@=2.3.1"
